data:
  dir: EX2/flower_dataset
  transforms:
  - type: RandomResizedCrop
    size: 224
  - type: RandomRotation
    degrees: 30
  - type: RandomHorizontalFlip
  - type: RandomVerticalFlip
  - type: ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  - type: ToTensor
  - type: Normalize
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  split_ratio:
  - 0.8
  - 0.2
model:
  name: resnet18
  pretrained: true
  num_classes: 5
training:
  batch_size: 32
  num_epochs: 25
  criterion: CrossEntropyLoss
  optimizer:
    type: SGD
    lr: 0.001
    momentum: 0.9
  scheduler:
    type: StepLR
    step_size: 7
    gamma: 0.1
meta:
  export_time: '2025-07-01T22:46:42.272770'
  author: '23831'
  python_version: 3.12.9
  torch_version: !!python/object/new:torch.torch_version.TorchVersion
  - 2.5.1
  torchvision_version: 0.20.1
